spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch-csv-reader
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  batch:
    job:
      enabled: false
    jdbc:
        initialize-schema: always

step:
  chunk : 100
input:
  file: classpath:data.csv

